version: "3.5"
services:
  TDengine:
    image: "datacenter/tdengine:1.6.4"
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.tdengine
    restart: always
    volumes:
      - type: volume
        source: TDengine_data
        target: /var/lib/taos
    ports:
      - "6030:6030"
  redis:
    image: "redis:5-alpine"
    restart: always
    ports:
      - "6379:6379"
  storage:
    image: datacenter/storage:1.0
    command: /usr/bin/storage
volumes:
  TDengine_data: {}
