list(APPEND CMAKE_LIBRARY_PATH "/usr/lib/x86_64-linux-gnu/")
find_path(MySQL_INCLUDE_DIR mysql/mysql.h)
if (WIN32)
find_library(MySQL_LIBRARIES libmariadb)
else(WIN32)
find_library(MySQL_LIBRARIES mysqlclient)
endif(WIN32)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MySQL DEFAULT_MSG MySQL_INCLUDE_DIR MySQL_LIBRARIES)